name: Deploy Flutter Web Preview to Firebase Hosting

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.2"  # Your Flutter version

      - name: Enable Web Support (optional)
        run: flutter config --enable-web

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: ⬇️ Download yt-dlp binary
        run: |
          echo "📥 Downloading yt-dlp ARM64 binary..."
          mkdir -p assets
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux_aarch64 -o assets/yt-dlp
          chmod +x assets/yt-dlp
          echo "✅ yt-dlp binary is ready in assets/"

      - name: Build Web App
        run: flutter build web

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NANCY_MUSIC_WORLD_66BD6 }}'
          projectId: 'nancy-music-world-66bd6'
          channelId: 'preview'
